services:

  frontend:
    build:
      context: ./frontend/music-app
      dockerfile: Dockerfile
    command: sh -c "yarn build && yarn start"
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/music-app:/app

  postgresql:
    build: ./postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"

  redis:
    build: ./redis
    ports:
     - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqadmin
      RABBITMQ_DEFAULT_PASS: rabbitmqadmin

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  minio_data:
