services:

  # frontend:
  #   build:
  #     context: ./frontend/music-app
  #     dockerfile: Dockerfile
  #   command: sh -c "yarn build && yarn start"
  #   container_name: nextjs-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: production
  #   volumes:
  #     - ./frontend/music-app:/app

  user-service:
    build: ./backend/user-service
    container_name: user-service
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy


  getaway:
    build: ./backend/getaway
    container_name: getaway
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - user-service

  postgresql:
    build: ./postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    build: ./redis
    ports:
     - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - minio_data:/data

  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqadmin
      RABBITMQ_DEFAULT_PASS: rabbitmqadmin

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  minio_data:
